language: ruby
rvm:
  - 2.1

before_script:
  # Ensure the script is executable
  - chmod +x ./script/cibuild.sh

script:
  # Run main ci script
  - ./script/cibuild.sh

after_success:
  # Push site to S3 if succeeded
  - s3_website push

env:
  global:
    # Speed up installation of html-proofer
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - secure: EvSHriDOIl4upUWw9cmzD0F3BMyghQRi3n6ZSw86TGmfpb7BboidaGLAfQUdm8EjgfmDeJ6QiKc4zZUUmnouaumE1kY3SsBsyISkyJzCddjeLn1UA4x1Xf5jaMjgwoI5B1hkzWx9LTUeaUmxRzpSVYHk/acPtvGFjMJUq1QzSFJwJhaEYQVvOsmMijwPVgPcQHX60lF38NhG+/hukzpVGRDD4g+gJ/TiZdHS36p0mfrLcRXus1YUFMhFjhYrUBWlnkesgQkDM/aeEYtefX++0V/gixxAds42bffvVUfLJkR8/V5qArqDZZygdRNvF9cTlQaX/+lymGB7ShmV8M3/2UjQMbY8eNQY8IG2KE59veQ8x6H5rU1rr/2teyU0FDxmKRC0u8ppUmZ2Qky0NuWtUh5qIugxdtJvsfqOb1Mp+WCYPqrdhDae5VhXkO5yiGVDqoFrPxXBLkja86a06Avg96P1bv9fxEMjRYeFtJIJs6cK609++fdX1yCRby6EDzG5LMVaUIUIlXQSORr97Df3lAwp0w6HuYW8IZA3rmkIkz+xaVXs9rWyYDuJvI5iO+vfLYwT0mLULhUhVKIYZFEXRLN5+9iK9V1h9ieaSp2zQ4OGihmW3N8wOme/WEBQPelVnoJ9BSqdPVdpD2qh9wT8XXNdYloLkWjjQrOnqsa72io=
    - secure: PenuxlBP1+ubNslOaTi34d7/Q30/EPUiBU9gtCEbdXwIikkb4qLT7ZCvQluBMI/X21tWGGEs+oKOyvgagoBSbsrp60fS7yHCLD0WD4Y9nYh0E4gFynVfMsM58kAhOOZllbmh77euzC8ipJrw1F1DQf7wrdf3ocCD1WsKlJuvtabHNY5ISA02eOd/M+TiU+0sFzviICyAxVixcNM2jxApGimK+jZIvFJhu3tBb/pqFUmg/EwiPYHY4qUL7VJd1mZEtwMdTdzrgSxW/kIIQzQ0bXEyinfjEKcOYUn3X/t/P+h+FrO6g6p0uBUrzyWViB2JMIxMJNbpGTKeewt9B2LAJZbZZ7lNti6VL86++AWL/9aLT4gc3WicZHLnWCAcS6bEcQFuanrhdfcd6H2pGlu7W6Ivu+VPr3dhdLl7cvybQksY7nqOuAVmatAtkx8rYCVs6Eij41hfGegkg65UcuiBtI/4xXpLawGuZ8SW8e2ByazXnD960Xfb+q+ts5tXlopUY9M+SSr1yVR7jMI0gWqBVK/zhCce5dimQeCGQMuJJ+0KJ647XFFMQ0uv2reChN+nqjR0eq5fQ1PBbYJNkoFFo2ACd6VclLlZSBL+TM5LoRjvlC7BDlQSfLWHhSwrQX05j+3a5EfzdVVXoILqyKN01NCaVXeIc3vqzQk7xzcB+Pc=
    - secure: Qo+s0mfUkDpBsF9NQLjtRiXhc4DLbavmDeToCfmPQVrDdwRgssSn3gOC+UDNP5T6h0yAKcIsZtBRPLdef+AKcuQmZbtQWh/WzNZEGDOGwjJ4vbbAn2/yjU5csLmZxeWivIr1pT26zv/mVkZlHV3A75GFkRtqeZ6hiDdwQD4TyPwIKp9nEXg3IlabyO5S1LGGLqOlkDKBAxXSVlb2GQhShTUE7CAdhzn+hxeQGIiq8tnZYGscnmbE7pofqWOpVITbPlt9Vz7vcsCJjWlN4PK4r8lVg3SofaKiwsfAegtTw8c/TKVzy7lg01rma5Ajdbv9MgITqMlaP8MSdbh7nTs0rY6G18Y30YpvIIxKU8Y49VMH1NOoFqUC3UhhH3AaAzJabPX7lDbqKxsoxhGbcZwTiMdxwWHk8GZWYO8CpdJFrIuXdPUXmNA2odasDIVn6Qz+U3k/Nol6bA3Jrhy1k4qKWW2hGeCxWgA9MJGODv9X+051b/cn38R1pY2xW0QiVlROrM3KxX+Nmot4K8ZVL3fh2J6aANQ8Wt7xRMTIdztRLQaCJQk2MyGMGHYLG+XgC/MkWceWYrGssTbwgE0oqtr4gZ9OJegcUK1VS0txv+Wc+tz4K8k11AEV3gYUQSUkN6tPb+Ymw3RjC0w6Zb6h4K1uagrGTZyCAjM6Yt0immz8Rwk=

sudo: false
