# The main config file for your Jenkyll template

# Site settings
title: clenemt
desc: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

url: http://clenemt.com
baseurl: '' # the subpath of your site, e.g. /blog
permalink: /:year/:title/

# Meta settings
email: clement.moron@gmail.com
author: Clement Moron
twitter_username: clenemt
github_username:  clenemt

# Optional settings
google_analytics: 'UA-XXXXXXXX-X'

# Pagination settings
paginate: 5
paginate_path: "/articles/page:num/"

# Navigation settings
navigation:
  - title: Articles
    url: /articles/
    desc: Read articles about the web ever changing techs and best practices
  - title: Projects
    url: /projects/
    desc: Projects that I have built in my spare time and that I am proud to showcase
  - title: Work
    url: /work/
    desc: Projects that I have worked on an that I thought you may find interesting
  - title: About
    url: /about/
    desc: Learn about me, my personal profile, my hobbies and some other coll stuffs

# Front Matter settings
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

# Markdown parser settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

# Build settings
include:
  - _pages
exclude:
  - README.md
  - vendor
gems:
  - jekyll-paginate

